package org.dewdrop.steamhelper.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table res_game_classification
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ResGameClassification {
	
	public ResGameClassification() {
	}
	
	public ResGameClassification(Integer id, String series, String subSeries) {
		this.id = id;
		this.series = series;
		this.subSeries = subSeries;
	}
	
	/**
     * Database Column Remarks:
     *   pk
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_game_classification.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   系列
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_game_classification.series
     *
     * @mbg.generated
     */
    private String series;

    /**
     * Database Column Remarks:
     *   子系列
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_game_classification.sub_series
     *
     * @mbg.generated
     */
    private String subSeries;

    /**
     * Database Column Remarks:
     *   简介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_game_classification.resume
     *
     * @mbg.generated
     */
    private String resume;

    /**
     * Database Column Remarks:
     *   分类标准
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_game_classification.standard
     *
     * @mbg.generated
     */
    private String standard;

    /**
     * Database Column Remarks:
     *   经典样例
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_game_classification.sample
     *
     * @mbg.generated
     */
    private String sample;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_game_classification.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_game_classification.id
     *
     * @return the value of res_game_classification.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_game_classification.id
     *
     * @param id the value for res_game_classification.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_game_classification.series
     *
     * @return the value of res_game_classification.series
     *
     * @mbg.generated
     */
    public String getSeries() {
        return series;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_game_classification.series
     *
     * @param series the value for res_game_classification.series
     *
     * @mbg.generated
     */
    public void setSeries(String series) {
        this.series = series == null ? null : series.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_game_classification.sub_series
     *
     * @return the value of res_game_classification.sub_series
     *
     * @mbg.generated
     */
    public String getSubSeries() {
        return subSeries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_game_classification.sub_series
     *
     * @param subSeries the value for res_game_classification.sub_series
     *
     * @mbg.generated
     */
    public void setSubSeries(String subSeries) {
        this.subSeries = subSeries == null ? null : subSeries.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_game_classification.resume
     *
     * @return the value of res_game_classification.resume
     *
     * @mbg.generated
     */
    public String getResume() {
        return resume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_game_classification.resume
     *
     * @param resume the value for res_game_classification.resume
     *
     * @mbg.generated
     */
    public void setResume(String resume) {
        this.resume = resume == null ? null : resume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_game_classification.standard
     *
     * @return the value of res_game_classification.standard
     *
     * @mbg.generated
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_game_classification.standard
     *
     * @param standard the value for res_game_classification.standard
     *
     * @mbg.generated
     */
    public void setStandard(String standard) {
        this.standard = standard == null ? null : standard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_game_classification.sample
     *
     * @return the value of res_game_classification.sample
     *
     * @mbg.generated
     */
    public String getSample() {
        return sample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_game_classification.sample
     *
     * @param sample the value for res_game_classification.sample
     *
     * @mbg.generated
     */
    public void setSample(String sample) {
        this.sample = sample == null ? null : sample.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_game_classification.sort
     *
     * @return the value of res_game_classification.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_game_classification.sort
     *
     * @param sort the value for res_game_classification.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}