package org.dewdrop.steamhelper.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_dict
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SysDict {
    /**
     * Database Column Remarks:
     *   pk
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   字典名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.dict_key
     *
     * @mbg.generated
     */
    private String dictKey;

    /**
     * Database Column Remarks:
     *   字典值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.dict_value
     *
     * @mbg.generated
     */
    private String dictValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.id
     *
     * @return the value of sys_dict.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.id
     *
     * @param id the value for sys_dict.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.dict_key
     *
     * @return the value of sys_dict.dict_key
     *
     * @mbg.generated
     */
    public String getDictKey() {
        return dictKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.dict_key
     *
     * @param dictKey the value for sys_dict.dict_key
     *
     * @mbg.generated
     */
    public void setDictKey(String dictKey) {
        this.dictKey = dictKey == null ? null : dictKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.dict_value
     *
     * @return the value of sys_dict.dict_value
     *
     * @mbg.generated
     */
    public String getDictValue() {
        return dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.dict_value
     *
     * @param dictValue the value for sys_dict.dict_value
     *
     * @mbg.generated
     */
    public void setDictValue(String dictValue) {
        this.dictValue = dictValue == null ? null : dictValue.trim();
    }
}