package org.dewdrop.steamhelper.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.dewdrop.steamhelper.entity.ResAccount;

public interface ResAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_account
     *
     * @mbg.generated
     */
    int insert(ResAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_account
     *
     * @mbg.generated
     */
    int insertSelective(ResAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_account
     *
     * @mbg.generated
     */
    ResAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ResAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ResAccount record);
	
	List<ResAccount> findAll(@Param("query") ResAccount query);
}