package org.dewdrop.steamhelper.mapper;

import java.util.List;

import org.dewdrop.steamhelper.entity.ResGameClassification;

public interface ResGameClassificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_game_classification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_game_classification
     *
     * @mbg.generated
     */
    int insert(ResGameClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_game_classification
     *
     * @mbg.generated
     */
    int insertSelective(ResGameClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_game_classification
     *
     * @mbg.generated
     */
    ResGameClassification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_game_classification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ResGameClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table res_game_classification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ResGameClassification record);
	
	List<ResGameClassification> findAll();
	
	List<String> getSeries();
}