package org.dewdrop.steamhelper.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.dewdrop.steamhelper.entity.SysMenu;

public interface SysMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated
     */
    int insert(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated
     */
    int insertSelective(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated
     */
    SysMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysMenu record);
	
	List<SysMenu> getListByRole(Integer roleId);
	
	List<SysMenu> getListByParentRole(@Param("pId") Integer pId, @Param("roleId") Integer roleId);
	
	List<SysMenu> getListByParent(@Param("pId") Integer pId);
	
	List<SysMenu> findAll(SysMenu query);
	
	List<SysMenu> getListByLevel(Integer level);
}