package com.wur7.store.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table res_account
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ResAccount {
    /**
     * Database Column Remarks:
     *   pk
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_account.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_account.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   平台id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_account.platform_id
     *
     * @mbg.generated
     */
    private Integer platformId;

    /**
     * Database Column Remarks:
     *   登录账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_account.login_name
     *
     * @mbg.generated
     */
    private String loginName;

    /**
     * Database Column Remarks:
     *   用户昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_account.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   在平台的用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_account.platform_user_id
     *
     * @mbg.generated
     */
    private Long platformUserId;

    /**
     * Database Column Remarks:
     *   在平台的用户编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_account.platform_user_no
     *
     * @mbg.generated
     */
    private String platformUserNo;

    /**
     * Database Column Remarks:
     *   在平台的用户id或编号【1：id；2：编号；...】
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_account.num_type
     *
     * @mbg.generated
     */
    private Integer numType;

    /**
     * Database Column Remarks:
     *   在平台的账号token
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_account.account_token
     *
     * @mbg.generated
     */
    private String accountToken;

    /**
     * Database Column Remarks:
     *   是否是该平台的主账号【1：是；0：否】
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_account.main_account
     *
     * @mbg.generated
     */
    private Integer mainAccount;

    /**
     * Database Column Remarks:
     *   账号排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_account.account_sort
     *
     * @mbg.generated
     */
    private Integer accountSort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_account.id
     *
     * @return the value of res_account.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_account.id
     *
     * @param id the value for res_account.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_account.user_id
     *
     * @return the value of res_account.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_account.user_id
     *
     * @param userId the value for res_account.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_account.platform_id
     *
     * @return the value of res_account.platform_id
     *
     * @mbg.generated
     */
    public Integer getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_account.platform_id
     *
     * @param platformId the value for res_account.platform_id
     *
     * @mbg.generated
     */
    public void setPlatformId(Integer platformId) {
        this.platformId = platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_account.login_name
     *
     * @return the value of res_account.login_name
     *
     * @mbg.generated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_account.login_name
     *
     * @param loginName the value for res_account.login_name
     *
     * @mbg.generated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_account.user_name
     *
     * @return the value of res_account.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_account.user_name
     *
     * @param userName the value for res_account.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_account.platform_user_id
     *
     * @return the value of res_account.platform_user_id
     *
     * @mbg.generated
     */
    public Long getPlatformUserId() {
        return platformUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_account.platform_user_id
     *
     * @param platformUserId the value for res_account.platform_user_id
     *
     * @mbg.generated
     */
    public void setPlatformUserId(Long platformUserId) {
        this.platformUserId = platformUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_account.platform_user_no
     *
     * @return the value of res_account.platform_user_no
     *
     * @mbg.generated
     */
    public String getPlatformUserNo() {
        return platformUserNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_account.platform_user_no
     *
     * @param platformUserNo the value for res_account.platform_user_no
     *
     * @mbg.generated
     */
    public void setPlatformUserNo(String platformUserNo) {
        this.platformUserNo = platformUserNo == null ? null : platformUserNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_account.num_type
     *
     * @return the value of res_account.num_type
     *
     * @mbg.generated
     */
    public Integer getNumType() {
        return numType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_account.num_type
     *
     * @param numType the value for res_account.num_type
     *
     * @mbg.generated
     */
    public void setNumType(Integer numType) {
        this.numType = numType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_account.account_token
     *
     * @return the value of res_account.account_token
     *
     * @mbg.generated
     */
    public String getAccountToken() {
        return accountToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_account.account_token
     *
     * @param accountToken the value for res_account.account_token
     *
     * @mbg.generated
     */
    public void setAccountToken(String accountToken) {
        this.accountToken = accountToken == null ? null : accountToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_account.main_account
     *
     * @return the value of res_account.main_account
     *
     * @mbg.generated
     */
    public Integer getMainAccount() {
        return mainAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_account.main_account
     *
     * @param mainAccount the value for res_account.main_account
     *
     * @mbg.generated
     */
    public void setMainAccount(Integer mainAccount) {
        this.mainAccount = mainAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_account.account_sort
     *
     * @return the value of res_account.account_sort
     *
     * @mbg.generated
     */
    public Integer getAccountSort() {
        return accountSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_account.account_sort
     *
     * @param accountSort the value for res_account.account_sort
     *
     * @mbg.generated
     */
    public void setAccountSort(Integer accountSort) {
        this.accountSort = accountSort;
    }
}