package com.wur7.store.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table shop_item_spec
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ShopItemSpec {
    /**
     * Database Column Remarks:
     *   pk
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item_spec.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item_spec.item_id
     *
     * @mbg.generated
     */
    private Integer itemId;

    /**
     * Database Column Remarks:
     *   规格名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item_spec.spec_name
     *
     * @mbg.generated
     */
    private String specName;

    /**
     * Database Column Remarks:
     *   供货价格（分）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item_spec.supply_price
     *
     * @mbg.generated
     */
    private Integer supplyPrice;

    /**
     * Database Column Remarks:
     *   销售价格（分）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item_spec.sale_price
     *
     * @mbg.generated
     */
    private Integer salePrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item_spec.id
     *
     * @return the value of shop_item_spec.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item_spec.id
     *
     * @param id the value for shop_item_spec.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item_spec.item_id
     *
     * @return the value of shop_item_spec.item_id
     *
     * @mbg.generated
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item_spec.item_id
     *
     * @param itemId the value for shop_item_spec.item_id
     *
     * @mbg.generated
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item_spec.spec_name
     *
     * @return the value of shop_item_spec.spec_name
     *
     * @mbg.generated
     */
    public String getSpecName() {
        return specName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item_spec.spec_name
     *
     * @param specName the value for shop_item_spec.spec_name
     *
     * @mbg.generated
     */
    public void setSpecName(String specName) {
        this.specName = specName == null ? null : specName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item_spec.supply_price
     *
     * @return the value of shop_item_spec.supply_price
     *
     * @mbg.generated
     */
    public Integer getSupplyPrice() {
        return supplyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item_spec.supply_price
     *
     * @param supplyPrice the value for shop_item_spec.supply_price
     *
     * @mbg.generated
     */
    public void setSupplyPrice(Integer supplyPrice) {
        this.supplyPrice = supplyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item_spec.sale_price
     *
     * @return the value of shop_item_spec.sale_price
     *
     * @mbg.generated
     */
    public Integer getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item_spec.sale_price
     *
     * @param salePrice the value for shop_item_spec.sale_price
     *
     * @mbg.generated
     */
    public void setSalePrice(Integer salePrice) {
        this.salePrice = salePrice;
    }
}