package com.wur7.store.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table shop_item
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ShopItem {
    /**
     * Database Column Remarks:
     *   pk
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   所属店铺id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.shop_id
     *
     * @mbg.generated
     */
    private Integer shopId;

    /**
     * Database Column Remarks:
     *   所属店铺名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.shop_name
     *
     * @mbg.generated
     */
    private String shopName;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.item_name
     *
     * @mbg.generated
     */
    private String itemName;

    /**
     * Database Column Remarks:
     *   商品编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.item_code
     *
     * @mbg.generated
     */
    private String itemCode;

    /**
     * Database Column Remarks:
     *   商品图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.item_image
     *
     * @mbg.generated
     */
    private String itemImage;

    /**
     * Database Column Remarks:
     *   商品类别【1：实体，2：虚拟】
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.item_type
     *
     * @mbg.generated
     */
    private Integer itemType;

    /**
     * Database Column Remarks:
     *   商品分类：1级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.item_category_1
     *
     * @mbg.generated
     */
    private Integer itemCategory1;

    /**
     * Database Column Remarks:
     *   商品分类：2级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.item_category_2
     *
     * @mbg.generated
     */
    private Integer itemCategory2;

    /**
     * Database Column Remarks:
     *   商品分类：3级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.item_category_3
     *
     * @mbg.generated
     */
    private Integer itemCategory3;

    /**
     * Database Column Remarks:
     *   品牌名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.brand_name
     *
     * @mbg.generated
     */
    private String brandName;

    /**
     * Database Column Remarks:
     *   型号类别【1：单一型号规格，2：多种型号规格】
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.model_type
     *
     * @mbg.generated
     */
    private Integer modelType;

    /**
     * Database Column Remarks:
     *   详情
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.item_detail
     *
     * @mbg.generated
     */
    private String itemDetail;

    /**
     * Database Column Remarks:
     *   快递费
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.delivery_fee
     *
     * @mbg.generated
     */
    private BigDecimal deliveryFee;

    /**
     * Database Column Remarks:
     *   快递免收额，达到该值则不收
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.delivery_threshold
     *
     * @mbg.generated
     */
    private BigDecimal deliveryThreshold;

    /**
     * Database Column Remarks:
     *   商品状态【1：上架，2：下架，3：草稿】
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.item_status
     *
     * @mbg.generated
     */
    private Integer itemStatus;

    /**
     * Database Column Remarks:
     *   创建者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.creator
     *
     * @mbg.generated
     */
    private Integer creator;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.id
     *
     * @return the value of shop_item.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.id
     *
     * @param id the value for shop_item.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.shop_id
     *
     * @return the value of shop_item.shop_id
     *
     * @mbg.generated
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.shop_id
     *
     * @param shopId the value for shop_item.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.shop_name
     *
     * @return the value of shop_item.shop_name
     *
     * @mbg.generated
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.shop_name
     *
     * @param shopName the value for shop_item.shop_name
     *
     * @mbg.generated
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.item_name
     *
     * @return the value of shop_item.item_name
     *
     * @mbg.generated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.item_name
     *
     * @param itemName the value for shop_item.item_name
     *
     * @mbg.generated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.item_code
     *
     * @return the value of shop_item.item_code
     *
     * @mbg.generated
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.item_code
     *
     * @param itemCode the value for shop_item.item_code
     *
     * @mbg.generated
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode == null ? null : itemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.item_image
     *
     * @return the value of shop_item.item_image
     *
     * @mbg.generated
     */
    public String getItemImage() {
        return itemImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.item_image
     *
     * @param itemImage the value for shop_item.item_image
     *
     * @mbg.generated
     */
    public void setItemImage(String itemImage) {
        this.itemImage = itemImage == null ? null : itemImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.item_type
     *
     * @return the value of shop_item.item_type
     *
     * @mbg.generated
     */
    public Integer getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.item_type
     *
     * @param itemType the value for shop_item.item_type
     *
     * @mbg.generated
     */
    public void setItemType(Integer itemType) {
        this.itemType = itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.item_category_1
     *
     * @return the value of shop_item.item_category_1
     *
     * @mbg.generated
     */
    public Integer getItemCategory1() {
        return itemCategory1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.item_category_1
     *
     * @param itemCategory1 the value for shop_item.item_category_1
     *
     * @mbg.generated
     */
    public void setItemCategory1(Integer itemCategory1) {
        this.itemCategory1 = itemCategory1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.item_category_2
     *
     * @return the value of shop_item.item_category_2
     *
     * @mbg.generated
     */
    public Integer getItemCategory2() {
        return itemCategory2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.item_category_2
     *
     * @param itemCategory2 the value for shop_item.item_category_2
     *
     * @mbg.generated
     */
    public void setItemCategory2(Integer itemCategory2) {
        this.itemCategory2 = itemCategory2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.item_category_3
     *
     * @return the value of shop_item.item_category_3
     *
     * @mbg.generated
     */
    public Integer getItemCategory3() {
        return itemCategory3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.item_category_3
     *
     * @param itemCategory3 the value for shop_item.item_category_3
     *
     * @mbg.generated
     */
    public void setItemCategory3(Integer itemCategory3) {
        this.itemCategory3 = itemCategory3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.brand_name
     *
     * @return the value of shop_item.brand_name
     *
     * @mbg.generated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.brand_name
     *
     * @param brandName the value for shop_item.brand_name
     *
     * @mbg.generated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.model_type
     *
     * @return the value of shop_item.model_type
     *
     * @mbg.generated
     */
    public Integer getModelType() {
        return modelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.model_type
     *
     * @param modelType the value for shop_item.model_type
     *
     * @mbg.generated
     */
    public void setModelType(Integer modelType) {
        this.modelType = modelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.item_detail
     *
     * @return the value of shop_item.item_detail
     *
     * @mbg.generated
     */
    public String getItemDetail() {
        return itemDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.item_detail
     *
     * @param itemDetail the value for shop_item.item_detail
     *
     * @mbg.generated
     */
    public void setItemDetail(String itemDetail) {
        this.itemDetail = itemDetail == null ? null : itemDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.delivery_fee
     *
     * @return the value of shop_item.delivery_fee
     *
     * @mbg.generated
     */
    public BigDecimal getDeliveryFee() {
        return deliveryFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.delivery_fee
     *
     * @param deliveryFee the value for shop_item.delivery_fee
     *
     * @mbg.generated
     */
    public void setDeliveryFee(BigDecimal deliveryFee) {
        this.deliveryFee = deliveryFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.delivery_threshold
     *
     * @return the value of shop_item.delivery_threshold
     *
     * @mbg.generated
     */
    public BigDecimal getDeliveryThreshold() {
        return deliveryThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.delivery_threshold
     *
     * @param deliveryThreshold the value for shop_item.delivery_threshold
     *
     * @mbg.generated
     */
    public void setDeliveryThreshold(BigDecimal deliveryThreshold) {
        this.deliveryThreshold = deliveryThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.item_status
     *
     * @return the value of shop_item.item_status
     *
     * @mbg.generated
     */
    public Integer getItemStatus() {
        return itemStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.item_status
     *
     * @param itemStatus the value for shop_item.item_status
     *
     * @mbg.generated
     */
    public void setItemStatus(Integer itemStatus) {
        this.itemStatus = itemStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.creator
     *
     * @return the value of shop_item.creator
     *
     * @mbg.generated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.creator
     *
     * @param creator the value for shop_item.creator
     *
     * @mbg.generated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.create_time
     *
     * @return the value of shop_item.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.create_time
     *
     * @param createTime the value for shop_item.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.update_time
     *
     * @return the value of shop_item.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.update_time
     *
     * @param updateTime the value for shop_item.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}