package com.wur7.store.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table shop_item_pic
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ShopItemPic {
    /**
     * Database Column Remarks:
     *   pk
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item_pic.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   所属商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item_pic.item_id
     *
     * @mbg.generated
     */
    private Integer itemId;

    /**
     * Database Column Remarks:
     *   url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item_pic.pic_url
     *
     * @mbg.generated
     */
    private String picUrl;

    /**
     * Database Column Remarks:
     *   排序（asc）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item_pic.sort_no
     *
     * @mbg.generated
     */
    private Integer sortNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item_pic.id
     *
     * @return the value of shop_item_pic.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item_pic.id
     *
     * @param id the value for shop_item_pic.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item_pic.item_id
     *
     * @return the value of shop_item_pic.item_id
     *
     * @mbg.generated
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item_pic.item_id
     *
     * @param itemId the value for shop_item_pic.item_id
     *
     * @mbg.generated
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item_pic.pic_url
     *
     * @return the value of shop_item_pic.pic_url
     *
     * @mbg.generated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item_pic.pic_url
     *
     * @param picUrl the value for shop_item_pic.pic_url
     *
     * @mbg.generated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item_pic.sort_no
     *
     * @return the value of shop_item_pic.sort_no
     *
     * @mbg.generated
     */
    public Integer getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item_pic.sort_no
     *
     * @param sortNo the value for shop_item_pic.sort_no
     *
     * @mbg.generated
     */
    public void setSortNo(Integer sortNo) {
        this.sortNo = sortNo;
    }
}