package com.wur7.store.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_item_category
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SysItemCategory {
    /**
     * Database Column Remarks:
     *   pk
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_item_category.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   父id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_item_category.p_id
     *
     * @mbg.generated
     */
    private Integer pId;

    /**
     * Database Column Remarks:
     *   类别名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_item_category.category_name
     *
     * @mbg.generated
     */
    private String categoryName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_item_category.id
     *
     * @return the value of sys_item_category.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_item_category.id
     *
     * @param id the value for sys_item_category.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_item_category.p_id
     *
     * @return the value of sys_item_category.p_id
     *
     * @mbg.generated
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_item_category.p_id
     *
     * @param pId the value for sys_item_category.p_id
     *
     * @mbg.generated
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_item_category.category_name
     *
     * @return the value of sys_item_category.category_name
     *
     * @mbg.generated
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_item_category.category_name
     *
     * @param categoryName the value for sys_item_category.category_name
     *
     * @mbg.generated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }
}