package com.wur7.store.mapper;

import java.util.List;

import com.wur7.store.entity.ShopItem;

public interface ShopItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item
     *
     * @mbg.generated
     */
    int insert(ShopItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item
     *
     * @mbg.generated
     */
    int insertSelective(ShopItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item
     *
     * @mbg.generated
     */
    ShopItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopItem record);
	
	List<ShopItem> findAll(ShopItem query);
}