package com.wur7.store.mapper;

import com.wur7.store.entity.ShopItemSpec;

public interface ShopItemSpecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item_spec
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item_spec
     *
     * @mbg.generated
     */
    int insert(ShopItemSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item_spec
     *
     * @mbg.generated
     */
    int insertSelective(ShopItemSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item_spec
     *
     * @mbg.generated
     */
    ShopItemSpec selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item_spec
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopItemSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item_spec
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopItemSpec record);
}