package com.wur7.store.mapper;

import com.wur7.store.entity.ShopItemPic;

public interface ShopItemPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item_pic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item_pic
     *
     * @mbg.generated
     */
    int insert(ShopItemPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item_pic
     *
     * @mbg.generated
     */
    int insertSelective(ShopItemPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item_pic
     *
     * @mbg.generated
     */
    ShopItemPic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item_pic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopItemPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item_pic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopItemPic record);
}