package com.wur7.store.mapper;

import org.apache.ibatis.annotations.Param;

import com.wur7.store.entity.ShopCustomer;

public interface ShopCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_customer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_customer
     *
     * @mbg.generated
     */
    int insert(ShopCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_customer
     *
     * @mbg.generated
     */
    int insertSelective(ShopCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_customer
     *
     * @mbg.generated
     */
    ShopCustomer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopCustomer record);
	
	ShopCustomer selectByOpenid(@Param("openid") String openid);
}