package com.wur7.store.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.wur7.store.entity.SysItemCategory;

public interface SysItemCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_item_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_item_category
     *
     * @mbg.generated
     */
    int insert(SysItemCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_item_category
     *
     * @mbg.generated
     */
    int insertSelective(SysItemCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_item_category
     *
     * @mbg.generated
     */
    SysItemCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_item_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysItemCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_item_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysItemCategory record);
	
	List<SysItemCategory> findByPid(@Param("pId") Integer pId);
}