package com.wur7.store.mapper;

import java.util.Set;

import org.apache.ibatis.annotations.Param;

import com.wur7.store.entity.SysRoleMenu;

public interface SysRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbg.generated
     */
    int insert(SysRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbg.generated
     */
    int insertSelective(SysRoleMenu record);
	
	Set<Integer> getMenuIdsByRole(@Param("roleId") Integer roleId);
	
	void delByRoleId(@Param("roleId") Integer roleId);
	
}